CREATE TABLE "tasks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(100),
  "completed" boolean DEFAULT false
);


//Tabla creada en dbdiagram, en este proyecto se uso una tabla diferente creada como modelo en el archivo (./models/tasks.models.js)